package com.example.schfit.util

import kotlin.random.Random

object MotivationProvider {

    private val quotesTr = listOf(
        "BugÃ¼n kendinin en iyi versiyonu ol!",
        "Disiplin, ne istediÄŸini ÅŸimdi ile neyi en Ã§ok istediÄŸin arasÄ±ndaki seÃ§imdir.",
        "Ter dÃ¶ktÃ¼ÄŸÃ¼n her damla, gelecekteki gÃ¼cÃ¼nÃ¼n temelidir.",
        "AÄŸrÄ± geÃ§icidir, ama zafer ve gurur kalÄ±cÄ±dÄ±r.",
        "Mazeretler kas yapmaz. Harekete geÃ§!",
        "Kendine inan; sÄ±nÄ±rlar sadece zihnindedir.",
        "BugÃ¼nkÃ¼ zorluk, yarÄ±nki kolaylÄ±ÄŸÄ±ndÄ±r.",
        "BÃ¼yÃ¼k baÅŸarÄ±lar, her gÃ¼n atÄ±lan kÃ¼Ã§Ã¼k adÄ±mlarla gelir.",
        "Aynadaki rakibini her gÃ¼n biraz daha geride bÄ±rak.",
        "Demir yalan sÃ¶ylemez; ne kadar verirsen o kadar alÄ±rsÄ±n.",
        "Her tekrar seni hedefine bir adÄ±m daha yaklaÅŸtÄ±rÄ±r.",
        "Yorulunca dinlenmeyi Ã¶ÄŸren, pes etmeyi deÄŸil.",
        "Sadece bedenin deÄŸil, iraden de gÃ¼Ã§leniyor.",
        "BaÅŸarÄ± ÅŸans eseri gelmez, terle inÅŸa edilir.",
        "Ä°lerleme yavaÅŸ olabilir ama pes edersen hiÃ§ olmaz.",
        "SÄ±nÄ±rlarÄ±nÄ± zorla, konfor alanÄ±nÄ±n bittiÄŸi yerde bÃ¼yÃ¼me baÅŸlar.",
        "Hedefine odaklan, bahaneleri kapÄ±da bÄ±rak.",
        "BugÃ¼n kaldÄ±racaÄŸÄ±n aÄŸÄ±rlÄ±k, yarÄ±nki Ã¶zgÃ¼venindir.",
        "Her ÅŸampiyon bir zamanlar pes etmeyi reddeden bir adaydÄ±.",
        "VÃ¼cudun her ÅŸeyi kaldÄ±rabilir; ikna etmen gereken tek ÅŸey zihnin.",
        "GÃ¼nÃ¼n en zor kÄ±smÄ± salona adÄ±m atmaktÄ±, gerisi senin eserin.",
        "Tutkunu gÃ¼ce, terini zafere dÃ¶nÃ¼ÅŸtÃ¼r.",
        "HiÃ§bir fÄ±rtÄ±na bir aÄŸacÄ±n kÃ¶klerini demir kadar gÃ¼Ã§lendiremez.",
        "Kendinle yarÄ±ÅŸ, dÃ¼n olduÄŸun kiÅŸiyi maÄŸlup et.",
        "Zorluklar seni yÄ±kmak iÃ§in deÄŸil, gÃ¼Ã§lendirmek iÃ§indir.",
        "Bir gÃ¼n deÄŸil, birinci gÃ¼n olsun!",
        "Sessizce Ã§alÄ±ÅŸ, baÅŸarÄ±n ses getirsin.",
        "VazgeÃ§meyi dÃ¼ÅŸÃ¼ndÃ¼ÄŸÃ¼nde, neden baÅŸladÄ±ÄŸÄ±nÄ± hatÄ±rla.",
        "KaslarÄ±n yanÄ±yorsa, deÄŸiÅŸim baÅŸlamÄ±ÅŸ demektir.",
        "Bahaneler 0 kalori yakar. Antrenmana odaklan!",
        "GeliÅŸim sabÄ±r ve sadakat ister; her sete deÄŸer ver.",
        "GÃ¼Ã§ sadece aÄŸÄ±rlÄ±k kaldÄ±rmak deÄŸil, zorluklara gÃ¶ÄŸÃ¼s germektir.",
        "Kendine yaptÄ±ÄŸÄ±n yatÄ±rÄ±m, en yÃ¼ksek getirisi olan yatÄ±rÄ±mdÄ±r.",
        "BugÃ¼n gÃ¶sterdiÄŸin Ã§aba, yarÄ±nki aynandaki tebessÃ¼mdÃ¼r.",
        "Her damla ter, hedefine giden yolda bir Ä±ÅŸÄ±ktÄ±r.",
        "Demir soÄŸuktur ama iÃ§inde yaktÄ±ÄŸÄ± ateÅŸ sonsuzdur.",
        "Kendi rekorunu kÄ±rmak iÃ§in harika bir gÃ¼n.",
        "Asla geriye bakma; o yÃ¶ne doÄŸru gitmiyorsun.",
        "Potansiyelini serbest bÄ±rak, limitlerini yeniden tanÄ±mla.",
        "YarÄ±n daha gÃ¼Ã§lÃ¼ uyanmak iÃ§in bugÃ¼n ter dÃ¶k.",
        "Ruhunu besle, bedenini eÄŸit, zihnini odakla.",
        "Zirveye Ã§Ä±kan yol her zaman dik ve meÅŸakkatlidir.",
        "Kazanmak alÄ±ÅŸkanlÄ±ktÄ±r; pes etmemek ise bir karakterdir.",
        "Bir sette daha diren, bir tekrar daha zorla!",
        "BugÃ¼nÃ¼n acÄ±sÄ±, yarÄ±nÄ±n gÃ¼cÃ¼dÃ¼r.",
        "Hayallerin iÃ§in savaÅŸ, kimse senin yerine o seti tamamlayamaz.",
        "GÃ¶zÃ¼nÃ¼ hedeften ayÄ±rma, her antrenman bir tuÄŸladÄ±r.",
        "ÅÃ¼phelerini kapÄ±da bÄ±rak, gÃ¼cÃ¼nÃ¼ serbest bÄ±rak.",
        "Sadece aÄŸÄ±rlÄ±k kaldÄ±rmÄ±yorsun, bir karakter inÅŸa ediyorsun.",
        "Tebrikler, bugÃ¼n de antrenmana Ã§Ä±ktÄ±n ve kazandÄ±n!"
    )

    private val quotesEn = listOf(
        "Be the best version of yourself today!",
        "Discipline is choosing between what you want now and what you want most.",
        "Every drop of sweat is the foundation of your future strength.",
        "Pain is temporary, but pride and victory are forever.",
        "Excuses don't build muscle. Take action!",
        "Believe in yourself; limits exist only in your mind.",
        "Today's struggle is tomorrow's ease.",
        "Great achievements come from small consistent daily steps.",
        "Outwork the competitor you see in the mirror every single day.",
        "The iron never lies; you get out exactly what you put in.",
        "Every single rep takes you one step closer to your goal.",
        "When you get tired, learn to rest, not to quit.",
        "You are not just forging your body, you are forging your will.",
        "Success doesn't happen by chance; it is built with sweat.",
        "Progress may be slow, but quitting won't speed it up.",
        "Push your boundaries; growth begins where comfort ends.",
        "Focus on your goal and leave excuses at the door.",
        "The weight you lift today is the confidence you wear tomorrow.",
        "Every champion was once a contender who refused to give up.",
        "Your body can stand almost anything; itâ€™s your mind you have to convince.",
        "The hardest part was walking through the door, the rest is your masterpiece.",
        "Turn your passion into power, and your sweat into victory.",
        "No storm strengthens roots the way the iron strengthens character.",
        "Compete with yourself; beat the person you were yesterday.",
        "Obstacles aren't meant to stop you, they are meant to build you.",
        "Don't say one day, make today day one!",
        "Work in silence; let your success make the noise.",
        "When you feel like quitting, remember why you started.",
        "If it burns, it means the transformation has begun.",
        "Excuses burn zero calories. Focus on the workout!",
        "Growth requires patience and loyalty; treat every set with purpose.",
        "Strength is not just lifting weights, it's overcoming adversity.",
        "Investing in yourself yields the highest possible returns.",
        "The effort you put in today is the smile you will wear tomorrow.",
        "Every drop of sweat lights up the path to your dream physique.",
        "The iron is cold, but the fire it ignites within you is eternal.",
        "Today is a brand new opportunity to smash your personal record.",
        "Never look back; you're not going that way.",
        "Unleash your true potential and redefine your limits.",
        "Sweat today so you can wake up stronger tomorrow.",
        "Feed your soul, train your body, sharpen your mind.",
        "The road to the summit is always steep and challenging.",
        "Winning is a habit; resilience is a character trait.",
        "Hold on for one more set, push for one more rep!",
        "Today's soreness is tomorrow's ultimate strength.",
        "Fight for your dreams; nobody else can lift that weight for you.",
        "Keep your eyes on the prize; every session is another brick in the wall.",
        "Leave your doubts behind and unleash your inner beast.",
        "You are not merely lifting weights; you are building an indomitable spirit.",
        "Great job showing up today and conquering the iron!"
    )

    private val quotesDe = listOf(
        "Sei heute die beste Version deiner selbst!",
        "Disziplin ist die Entscheidung zwischen dem, was du jetzt willst, und dem, was du am meisten willst.",
        "Jeder SchweiÃŸtropfen ist das Fundament deiner zukÃ¼nftigen StÃ¤rke.",
        "Schmerz vergeht, aber Stolz und Triumph bleiben fÃ¼r immer.",
        "Ausreden bauen keine Muskeln auf. Werde aktiv!",
        "Glaube an dich; Grenzen existieren nur in deinem Kopf.",
        "Die Anstrengung von heute ist die Leichtigkeit von morgen.",
        "GroÃŸe Erfolge entstehen durch tÃ¤gliche kleine Schritte.",
        "Besiege jeden Tag den Gegner, den du im Spiegel siehst.",
        "Das Eisen lÃ¼gt nie; du bekommst genau das zurÃ¼ck, was du investierst.",
        "Jede einzelne Wiederholung bringt dich deinem Ziel nÃ¤her.",
        "Lerne dich auszuruhen, wenn du mÃ¼de bist, nicht aufzugeben.",
        "Du stÃ¤hlst nicht nur deinen KÃ¶rper, sondern auch deinen Willen.",
        "Erfolg ist kein Zufall; er wird durch SchweiÃŸ geschmiedet.",
        "Fortschritt braucht Zeit, aber Aufgeben beschleunigt ihn nicht.",
        "Erweitere deine Grenzen; Wachstum beginnt auÃŸerhalb der Komfortzone.",
        "Fokussiere dich auf dein Ziel und lass Ausreden vor der TÃ¼r.",
        "Das Gewicht, das du heute hebst, ist dein Selbstvertrauen von morgen.",
        "Jeder Champion war einmal ein KÃ¤mpfer, der niemals aufgab.",
        "Dein KÃ¶rper schafft fast alles; du musst nur deinen Geist Ã¼berzeugen.",
        "Der schwerste Schritt war durch die TÃ¼r zu gehen â€“ der Rest ist dein Werk.",
        "Verwandle Leidenschaft in Kraft und SchweiÃŸ in Sieg.",
        "Harte Arbeit schlÃ¤gt Talent, wenn Talent nicht hart arbeitet.",
        "Konkurriere nur mit dir selbst; sei besser als gestern.",
        "Herausforderungen sind da, um dich stÃ¤rker zu machen.",
        "Sag nicht 'Eines Tages', mach heute zu Tag Eins!",
        "Arbeite im Stillen, lass deinen Erfolg sprechen.",
        "Wenn du aufgeben willst, denk daran, warum du angefangen hast.",
        "Wenn es brennt, hat die VerÃ¤nderung bereits begonnen.",
        "Ausreden verbrennen keine Kalorien. Voller Fokus!",
        "Wachstum verlangt Geduld und Hingabe; gib jedem Satz Bedeutung.",
        "StÃ¤rke bedeutet nicht nur Eisen zu heben, sondern HÃ¼rden zu meistern.",
        "Die Investition in dich selbst bringt die hÃ¶chsten Zinsen.",
        "Dein Einsatz heute ist dein LÃ¤cheln vor dem Spiegel morgen.",
        "Jeder Tropfen SchweiÃŸ beleuchtet deinen Weg zum Ziel.",
        "Das Eisen ist kalt, aber das Feuer in dir ist unbezwingbar.",
        "Heute ist der perfekte Tag, um deine Bestleistung zu brechen.",
        "Schau nicht zurÃ¼ck; du gehst nicht in diese Richtung.",
        "Entfessle dein Potenzial und definiere deine Grenzen neu.",
        "Schwitze heute, um morgen stÃ¤rker aufzuwachen.",
        "NÃ¤hre deine Seele, trainiere deinen KÃ¶rper, schÃ¤rfe deinen Geist.",
        "Der Weg zum Gipfel ist steil, aber die Aussicht lohnt sich.",
        "Siegen ist eine Gewohnheit; Durchhalten ist Charakter.",
        "Halte noch einen Satz durch, kÃ¤mpfe um eine weitere Wiederholung!",
        "Der Muskelkater von heute ist die Kraft von morgen.",
        "KÃ¤mpfe fÃ¼r deine TrÃ¤ume; niemand sonst hebt das Gewicht fÃ¼r dich.",
        "Behalte das Ziel fest im Blick; jedes Training zÃ¤hlt.",
        "Lass Zweifel hinter dir und entfessle deine Kraft.",
        "Du hebst nicht nur Gewichte, du formst eine unbesiegbare MentalitÃ¤t.",
        "Klasse Leistung, dass du heute da warst und alles gegeben hast!"
    )

    private val quotesEs = listOf(
        "Â¡SÃ© la mejor versiÃ³n de ti mismo hoy!",
        "La disciplina es elegir entre lo que quieres ahora y lo que mÃ¡s deseas.",
        "Cada gota de sudor es la base de tu fuerza futura.",
        "El dolor es temporal, pero el orgullo y la victoria son eternos.",
        "Las excusas no construyen mÃºsculo. Â¡Pasa a la acciÃ³n!",
        "Cree en ti; los lÃ­mites solo existen en tu mente.",
        "El esfuerzo de hoy es la facilidad de maÃ±ana.",
        "Los grandes logros surgen de pequeÃ±os pasos diarios y constantes.",
        "Supera cada dÃ­a al rival que ves en el espejo.",
        "El hierro nunca miente; obtienes exactamente lo que entregas.",
        "Cada repeticiÃ³n te acerca un paso mÃ¡s a tu objetivo.",
        "Cuando te canses, aprende a descansar, no a rendirte.",
        "No solo estÃ¡s esculpiendo tu cuerpo, estÃ¡s forjando tu voluntad.",
        "El Ã©xito no ocurre por casualidad; se construye con sudor.",
        "El progreso puede ser lento, pero rendirse no lo acelerarÃ¡.",
        "DesafÃ­a tus lÃ­mites; el crecimiento comienza fuera de tu zona de confort.",
        "EnfÃ³cate en tu meta y deja las excusas en la puerta.",
        "El peso que levantas hoy es la confianza que vestirÃ¡s maÃ±ana.",
        "Todo campeÃ³n fue alguna vez un contendiente que se negÃ³ a rendirse.",
        "Tu cuerpo aguanta casi todo; es a tu mente a quien debes convencer.",
        "La parte mÃ¡s difÃ­cil fue cruzar la puerta, el resto es tu obra maestra.",
        "Transforma tu pasiÃ³n en poder y tu sudor en victoria.",
        "El trabajo duro vence al talento cuando el talento no trabaja duro.",
        "Compite contigo mismo; sÃ© mejor que la persona que fuiste ayer.",
        "Los obstÃ¡culos no estÃ¡n ahÃ­ para detenerte, sino para fortalecerte.",
        "Â¡No digas algÃºn dÃ­a, haz que hoy sea el dÃ­a uno!",
        "Trabaja en silencio; deja que tu Ã©xito haga todo el ruido.",
        "Cuando pienses en rendirte, recuerda por quÃ© empezaste.",
        "Si arde, significa que la transformaciÃ³n ha comenzado.",
        "Las excusas queman cero calorÃ­as. Â¡ConcÃ©ntrate en la sesiÃ³n!",
        "El crecimiento requiere paciencia y constancia; dale valor a cada serie.",
        "La fuerza no es solo levantar peso, es superar la adversidad.",
        "Invertir en ti mismo ofrece los mayores beneficios.",
        "El esfuerzo que pones hoy es la sonrisa frente al espejo maÃ±ana.",
        "Cada gota de sudor ilumina el camino hacia tu mejor versiÃ³n.",
        "El hierro es frÃ­o, pero el fuego que enciende en ti es eterno.",
        "Hoy es un gran dÃ­a para batir tu rÃ©cord personal.",
        "Nunca mires atrÃ¡s; no vas en esa direcciÃ³n.",
        "Libera tu verdadero potencial y redefine tus propios lÃ­mites.",
        "Suda hoy para despertar mucho mÃ¡s fuerte maÃ±ana.",
        "Alimenta tu espÃ­ritu, entrena tu cuerpo y enfoca tu mente.",
        "El camino hacia la cima siempre es empinado y desafiante.",
        "Ganar es un hÃ¡bito; perseverar es puro carÃ¡cter.",
        "Â¡Aguanta una serie mÃ¡s, lucha por una repeticiÃ³n mÃ¡s!",
        "Las agujetas de hoy son la potencia y resistencia de maÃ±ana.",
        "Lucha por tus sueÃ±os; nadie levantarÃ¡ ese peso por ti.",
        "MantÃ©n los ojos en el objetivo; cada entrenamiento es un ladrillo mÃ¡s.",
        "Deja las dudas atrÃ¡s y desata toda tu energÃ­a.",
        "No solo levantas pesas, estÃ¡s construyendo una mentalidad imparable.",
        "Â¡Gran trabajo entrenando hoy y conquistando el gimnasio!"
    )

    private val quotesIt = listOf(
        "Sii la versione migliore di te stesso oggi!",
        "La disciplina Ã¨ scegliere tra ciÃ² che vuoi ora e ciÃ² che desideri di piÃ¹.",
        "Ogni goccia di sudore Ã¨ la base della tua forza futura.",
        "Il dolore Ã¨ temporaneo, ma l'orgoglio e la vittoria sono per sempre.",
        "Le scuse non costruiscono muscoli. Agisci ora!",
        "Credi in te stesso; i limiti esistono solo nella tua mente.",
        "Lo sforzo di oggi Ã¨ la facilitÃ  di domani.",
        "I grandi traguardi nascono da piccoli passi quotidiani costanti.",
        "Batti ogni giorno l'avversario che vedi riflesso nello specchio.",
        "Il ferro non mente mai; ricevi esattamente quanto investi.",
        "Ogni singola ripetizione ti porta un passo piÃ¹ vicino alla meta.",
        "Quando sei stanco impara a riposare, non a mollare.",
        "Non stai solo forgiando il tuo corpo, stai scolpendo la tua volontÃ .",
        "Il successo non capita per caso; si costruisce con il sudore.",
        "I progressi possono essere lenti, ma arrendersi non li renderÃ  piÃ¹ veloci.",
        "Supera i tuoi limiti; la vera crescita inizia fuori dalla zona di comfort.",
        "Concentrati sul tuo obiettivo e lascia le scuse fuori dalla porta.",
        "Il carico che sollevi oggi Ã¨ la sicurezza che indosserai domani.",
        "Ogni campione Ã¨ stato un lottatore che ha rifiutato di arrendersi.",
        "Il tuo corpo puÃ² sopportare quasi tutto; Ã¨ la mente che devi convincere.",
        "La parte piÃ¹ dura Ã¨ stata varcare la soglia, il resto Ã¨ il tuo capolavoro.",
        "Trasforma la tua passione in potenza e il sudore in trionfo.",
        "Il duro lavoro batte il talento se il talento non lavora sodo.",
        "Gareggia solo con te stesso; sii migliore di chi eri ieri.",
        "Gli ostacoli non servono a fermarti, ma a renderti imbattibile.",
        "Non dire 'un giorno', fai in modo che oggi sia il Giorno Uno!",
        "Lavora in silenzio; lascia che sia il tuo successo a fare rumore.",
        "Quando pensi di mollare, ricordati perchÃ© hai iniziato.",
        "Se brucia, significa che la trasformazione Ã¨ appena iniziata.",
        "Le scuse bruciano zero calorie. Concentrati sull'allenamento!",
        "La crescita richiede pazienza e costanza; onora ogni singola serie.",
        "La vera forza non Ã¨ solo sollevare ghisa, ma superare le difficoltÃ .",
        "Investire su te stesso produce i rendimenti piÃ¹ alti in assoluto.",
        "L'impegno che metti oggi Ã¨ il sorriso davanti allo specchio domani.",
        "Ogni goccia di sudore illumina la strada verso il tuo obiettivo.",
        "Il ferro Ã¨ freddo, ma il fuoco che accende in te Ã¨ inarrestabile.",
        "Oggi Ã¨ il giorno ideale per superare il tuo record personale.",
        "Non guardare indietro; non Ã¨ quella la direzione in cui stai andando.",
        "Sprigiona il tuo potenziale e ridefinisci i tuoi confini.",
        "Suda oggi per svegliarti piÃ¹ forte domani.",
        "Nutri il tuo spirito, allena il tuo corpo, affila la tua mente.",
        "La salita verso la vetta Ã¨ sempre ripida, ma il panorama ripaga tutto.",
        "Vincere Ã¨ un'abitudine; non mollare Ã¨ carattere.",
        "Resisti per un'altra serie, lotta per un'altra ripetizione!",
        "I dolori muscolari di oggi sono la forza esplosiva di domani.",
        "Combatti per i tuoi sogni; nessun altro solleverÃ  quel carico al tuo posto.",
        "Tieni gli occhi fissi sull'obiettivo; ogni sessione Ã¨ fondamentale.",
        "Lascia i dubbi alle spalle e scatena tutta la tua grinta.",
        "Non stai solo sollevando pesi, stai costruendo uno spirito indomabile.",
        "Ottimo lavoro per esserti allenato oggi e aver dominato la ghisa!"
    )

    fun getRandomQuote(languageCode: String): String {
        val list = when (languageCode.lowercase()) {
            "en" -> quotesEn
            "de" -> quotesDe
            "es" -> quotesEs
            "it" -> quotesIt
            else -> quotesTr
        }
        return list[Random.nextInt(list.size)]
    }

    fun getDailyQuote(languageCode: String, daySeed: Long): String {
        val list = when (languageCode.lowercase()) {
            "en" -> quotesEn
            "de" -> quotesDe
            "es" -> quotesEs
            "it" -> quotesIt
            else -> quotesTr
        }
        val safeSeed = if (daySeed < 0) -daySeed else daySeed
        val index = (safeSeed % list.size).toInt()
        return list[index]
    }
}